title: 'How to get hacks '
description: This make u get aimbot and if u play nitro type this will get mocros
template:
  repo: how-to-get-hacks-template
  name: how-to-get-hacks
before:
  - type: createIssue
    title: Welcome!
    body: new-issue.md
steps:
  - title: First step
    description: The first step in your course
    event: issues.assigned
    link: '{{ repoUrl }}'
    actions:
      - type: closeIssue
